class ContactEditPage:
    LOCATOR_INPUT_FIRST_NAME = '//input[@id="firstName"]'
    LOCATOR_INPUT_LAST_NAME = '//input[@id="lastName"]'
    LOCATOR_INPUT_DATE_OF_BIRTH = '//input[@id="birthdate"]'
    LOCATOR_INPUT_EMAIL = '//input[@id="email"]'
    LOCATOR_INPUT_PHONE = '//input[@id="phone"]'
    LOCATOR_INPUT_STR_ADDRESS_ONE = '//input[@id="street1"]'
    LOCATOR_INPUT_STR_ADDRESS_TWO = '//input[@id="street2"]'
    LOCATOR_INPUT_CITY = '//input[@id="city"]'
    LOCATOR_INPUT_STATE_OF_PROVINCE = '//input[@id="stateProvince"]'
    LOCATOR_INPUT_POSTAL_CODE = '//input[@id="postalCode"]'
    LOCATOR_INPUT_COUNTRY = '//input[@id="country"]'
